package: yform_content_builder
version: '1.3.0'
author: 'KLXM Crossmedia / Thomas Skerbis'
supportpage: 'https://klxm.de'

requires:
    packages:
        yform: '>=4.0'
    redaxo: '^5.15'
    php:
        version: '^8.1'

page:
    title: 'translate:yform_content_builder_title'
    icon: rex-icon fa-puzzle-piece
    perm: admin
    subpages:
        main:
            title: 'translate:yform_content_builder_overview'
            icon: rex-icon fa-info-circle
        modules:
            title: 'translate:yform_content_builder_modules'
            icon: rex-icon fa-code
        settings:
            title: 'translate:yform_content_builder_settings'
            icon: rex-icon fa-cog
