package: yform_content_builder
version: '3.2.1'
author: 'Friends of REDAXO'
supportpage: 'https://klxm.de'
license: MIT

requires:
    packages:
        yform: '>=4.0'
        focuspoint: '>=4.0'
    redaxo: '^5.15'
    php:
        version: '^8.1'

page:
    title: 'translate:yform_content_builder_title'
    icon: rex-icon fa-puzzle-piece
    perm: admin
    subpages:
        main:
            title: 'translate:yform_content_builder_overview'
            icon: rex-icon fa-info-circle
        modules:
            title: 'translate:yform_content_builder_modules'
            icon: rex-icon fa-code
        media_types_preview:
            title: 'translate:yform_content_builder_media_types_preview'
            icon: rex-icon fa-image
        settings:
            title: 'translate:yform_content_builder_settings'
            icon: rex-icon fa-cog
        docs:
            title: 'translate:yform_content_builder_docs'
            icon: rex-icon fa-book
        dev:
            title: 'translate:yform_content_builder_dev'
            icon: rex-icon fa-code
        api:
            title: 'translate:yform_content_builder_api'
            icon: rex-icon fa-code-fork
        tutorial:
            title: 'translate:yform_content_builder_tutorial'
            icon: rex-icon fa-graduation-cap
